name: AuditHub integration

on:
    push:
        branches: [main]
    pull_request: 
        branches: [main]

env:
    AUDITHUB_BASE_URL: ${{ secrets.AUDITHUB_BASE_URL }}
    AUDITHUB_OIDC_CONFIGURATION_URL: ${{ secrets.AUDITHUB_OIDC_CONFIGURATION_URL }}
    AUDITHUB_OIDC_CLIENT_ID: ${{ secrets.AUDITHUB_OIDC_CLIENT_ID }}
    AUDITHUB_OIDC_CLIENT_SECRET: ${{ secrets.AUDITHUB_OIDC_CLIENT_SECRET }}
    AUDITHUB_ORGANIZATION_ID: ${{ secrets.AUDITHUB_ORGANIZATION_ID }}
    AUDITHUB_PROJECT_ID: ${{ secrets.AUDITHUB_PROJECT_ID }}

jobs:
    run-ah-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                python-version: "3.12"
            - name: Install AuditHub client
              run: pip install audithub-client
            - name: Run DeFi Vanguard
              run: ./ah-scripts/run-vanguard.sh ${{ github.sha }}
            # TODO: move all sarif files into a directory and pass that through the "sarif_file"
            - name: Upload unchecked-return results
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: unchecked-return.sarif
            # Commenting this out as there is an issue with the emitted sarif.
            # - name: Upload use-before-def results
            #   uses: github/codeql-action/upload-sarif@v3
            #   with:
            #     sarif_file: use-before-def.sarif
            - name: Run OrCa
              run: bash ./ah-scripts/run-orca-on-all-specs.sh ${{ github.sha }} specs/only-pm-submit.spec specs/freelancer-rank-invariant.spec specs/join-required-rank.spec specs/registration-rank.spec
